### ISSUE TITLE
[Bug Report] Server crashing on second player join (1.2.7)

### ISSUE THREAD

**Issue by EmlaSweetheart** [Benjamin-Norton/RandoAssistant#19]
![IMG_20230523_194643](https://github.com/Benjamin-Norton/RandoAssistant/assets/134331042/8884e7ec-72cd-4db3-9de7-7419ec8903a8)

The other user was able to connect to multiplayer but started decending to the void immediately when joining and then got disconnected with the message that I attached...
I have the latest.log if you want it sent to you. Where can I send it in that case?

**Comment by Benjamin-Norton** [comment]
In future you can upload files directly to GitHub in a comment. I know why it's breaking this time though as that error is a catch I added myself, so I won't need it.
It's hard to test multiplayer so I'll see if I can figure out what's causing it and try to patch this issue.

**Comment by Benjamin-Norton** [comment]
<img width="1915" alt="Screenshot 2023-05-23 at 4 13 28 PM" src="https://github.com/Benjamin-Norton/RandoAssistant/assets/18416784/2e3cbafc-fcd0-446c-95de-52bbc9b9afd7">

Fixed in 1.3.0, I also changed a bunch of stuff in the backend so the mod now fully supports servers (afaik, didn't manage to crash it :) ).
